# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getKappaC0zv <- function(X, t1, t2, t3) {
    .Call('_gofar_getKappaC0zv', PACKAGE = 'gofar', X, t1, t2, t3)
}

familyLinkinv3 <- function(X, t1, t2, t3) {
    .Call('_gofar_familyLinkinv3', PACKAGE = 'gofar', X, t1, t2, t3)
}

absT <- function(Xm) {
    .Call('_gofar_absT', PACKAGE = 'gofar', Xm)
}

nzcount <- function(x) {
    .Call('_gofar_nzcount', PACKAGE = 'gofar', x)
}

softThres <- function(x, lambda) {
    .Call('_gofar_softThres', PACKAGE = 'gofar', x, lambda)
}

softT <- function(x, lambda) {
    .Call('_gofar_softT', PACKAGE = 'gofar', x, lambda)
}

logisticlik <- function(Y, MU, nind) {
    .Call('_gofar_logisticlik', PACKAGE = 'gofar', Y, MU, nind)
}

gausslikehood <- function(Y, MU, Phi, nind) {
    .Call('_gofar_gausslikehood', PACKAGE = 'gofar', Y, MU, Phi, nind)
}

poissonlik <- function(Y, MU, nind) {
    .Call('_gofar_poissonlik', PACKAGE = 'gofar', Y, MU, nind)
}

poissondev <- function(Y, MU, nind) {
    .Call('_gofar_poissondev', PACKAGE = 'gofar', Y, MU, nind)
}

objfun3 <- function(Y, MU, Phi, t1, t2, t3, msind, naind) {
    .Call('_gofar_objfun3', PACKAGE = 'gofar', Y, MU, Phi, t1, t2, t3, msind, naind)
}

getdeviance <- function(Y, MU, Phi, t1, t2, t3, msind, naind) {
    .Call('_gofar_getdeviance', PACKAGE = 'gofar', Y, MU, Phi, t1, t2, t3, msind, naind)
}

mySdiff <- function(x, y) {
    .Call('_gofar_mySdiff', PACKAGE = 'gofar', x, y)
}

gcure_cpp_init2 <- function(Y, X0, rnk, cindex, ofset, familygroup, Zini, PhiIni, kappaC0, control, msind, naind, ndev) {
    .Call('_gofar_gcure_cpp_init2', PACKAGE = 'gofar', Y, X0, rnk, cindex, ofset, familygroup, Zini, PhiIni, kappaC0, control, msind, naind, ndev)
}

gcure_cpp_miss <- function(Y, Xm, nlam, cindex, ofset, familygroup, initw, Dini, Zini, PhiIni, Uini, Vini, kappaC0, lmax, control, msind, naind, ndev, eea, zerosol, maxit, epsilon) {
    .Call('_gofar_gcure_cpp_miss', PACKAGE = 'gofar', Y, Xm, nlam, cindex, ofset, familygroup, initw, Dini, Zini, PhiIni, Uini, Vini, kappaC0, lmax, control, msind, naind, ndev, eea, zerosol, maxit, epsilon)
}

